---
version: 2.1

jobs:
  compile:
    docker:
    - image: cimg/go:1.18
    steps:
    - checkout
    - run: make

  test:
    parameters:
      go_version:
        type: string
      run_test:
        type: boolean
        default: true
    docker:
    - image: cimg/go:<< parameters.go_version >>
    steps:
    - checkout
    - run: make test

workflows:
  version: 2
  unit-test:
    jobs:
    - compile
    - test:
        name: testing
        matrix:
          parameters:
            go_version:
            - "1.16"
            - "1.17"
            - "1.18"
            - "1.19"
