name: build-and-test-tablizer
on: [push]
jobs:
  build:
    strategy:
      matrix:
        version: ['1.23']
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go ${{ matrix.version }}
      uses: actions/setup-go@v5
      with:
        go-version: '${{ matrix.version }}'
      id: go

    - name: checkout
      uses: actions/checkout@v5

    - name: build
      run: make

    - name: test
      run: make test

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - uses: actions/checkout@v5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          skip-cache: true
